# Quick start

In [75]:
import numpy as np
a=np.arange(0,15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
a.shape

(3, 5)

In [77]:
a.ndim

2

In [78]:
a.dtype.name

'int64'

In [79]:
a.itemsize

8

In [80]:
a.size

15

In [81]:
type(a)

numpy.ndarray

In [82]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [83]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [86]:
np.linspace(0,2*np.pi)

array([0.        , 0.12822827, 0.25645654, 0.38468481, 0.51291309,
       0.64114136, 0.76936963, 0.8975979 , 1.02582617, 1.15405444,
       1.28228272, 1.41051099, 1.53873926, 1.66696753, 1.7951958 ,
       1.92342407, 2.05165235, 2.17988062, 2.30810889, 2.43633716,
       2.56456543, 2.6927937 , 2.82102197, 2.94925025, 3.07747852,
       3.20570679, 3.33393506, 3.46216333, 3.5903916 , 3.71861988,
       3.84684815, 3.97507642, 4.10330469, 4.23153296, 4.35976123,
       4.48798951, 4.61621778, 4.74444605, 4.87267432, 5.00090259,
       5.12913086, 5.25735913, 5.38558741, 5.51381568, 5.64204395,
       5.77027222, 5.89850049, 6.02672876, 6.15495704, 6.28318531])

In [87]:
%reset -f

In [88]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
a=np.array([[1,2],[3,4]])
np.asarray(a)

array([[1, 2],
       [3, 4]])

## Basic Operation

In [89]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([8,7,6,5])
a+b

array([9, 9, 9, 9])

In [90]:
a-b

array([-7, -5, -3, -1])

In [91]:
a*b

array([ 8, 14, 18, 20])

In [92]:
a/b

array([0.125     , 0.28571429, 0.5       , 0.8       ])

In [93]:
a<10

array([ True,  True,  True,  True])

In [94]:
a.dot(b)

60

In [95]:
%reset -f

In [96]:
import numpy as np
a=np.arange(0,6).reshape(3,2)
b=np.arange(6,0,-1).reshape(2,3)

In [97]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [98]:
b

array([[6, 5, 4],
       [3, 2, 1]])

In [99]:
b.dot(a)

array([[26, 41],
       [ 8, 14]])

In [100]:
a.dot(b)

array([[ 3,  2,  1],
       [21, 16, 11],
       [39, 30, 21]])

In [101]:
%reset -f

## Slice Index Iteration

In [102]:
import numpy as np
a=np.arange(0,10)

In [103]:
a[2]

2

In [104]:
a[2:5]

array([2, 3, 4])

In [105]:
a[:6:2]=0

In [106]:
a[::-1]

array([9, 8, 7, 6, 5, 0, 3, 0, 1, 0])

In [107]:
%reset -f

### Advanced indexing

In [108]:
import numpy as np
a=np.arange(1,10)
index=[1,1,2,2,3,3,5]
a[index]

array([2, 2, 3, 3, 4, 4, 6])

In [109]:
index = np.array([[1, 2],
                  [4, 5]])
a[index]


array([[2, 3],
       [5, 6]])

In [110]:
%reset -f

In [111]:
import numpy as np
a = np.arange(0, 12).reshape(3, 4)
print(a)
i = np.array([[0, 1], [1, 2]])  # get row 0, row 1, row 1, row 2
j = np.array([[1, 2], [3, 3]])
a[i]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [112]:
a[i,j] # get a[0,1], a[1,2], a[1,3] a[2,3]

array([[ 1,  6],
       [ 7, 11]])

In [113]:
%reset -f

### Bool indexing

In [114]:
import numpy as np
a=np.arange(0,10).reshape((2,5))
b_index=a>3
b_index

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [115]:
a[b_index]

array([4, 5, 6, 7, 8, 9])

In [116]:
%reset -f

### Get max

In [117]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd

time=np.linspace(20,145,5)
data=np.sin(np.arange(20)).reshape(5,4)
print(time)
print(data)
ind=data.argmax(axis=0)
print(ind)
time_max=time[ind]
print(time_max)
data_max=data[ind,range(data.shape[1])]
print(data_max)
print(data.max())

[ 20.    51.25  82.5  113.75 145.  ]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 82.5   20.   113.75  51.25]
[0.98935825 0.84147098 0.99060736 0.6569866 ]
0.9906073556948704


## Use function to generate matrix

In [118]:
import numpy as np
def gen(x,y):
    return 10*x+y

a=np.fromfunction(gen,(5,4))
print(a)

[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]
 [30. 31. 32. 33.]
 [40. 41. 42. 43.]]


In [119]:
a[2,3]

23.0

In [120]:
a[:,1] ## get second element of each row

array([ 1., 11., 21., 31., 41.])

In [121]:
a[1:3,:]## get [1,3) row

array([[10., 11., 12., 13.],
       [20., 21., 22., 23.]])

In [122]:
for row in a:
    print(row)

[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
[30. 31. 32. 33.]
[40. 41. 42. 43.]


In [123]:
b=a.flat
print(*b)

0.0 1.0 2.0 3.0 10.0 11.0 12.0 13.0 20.0 21.0 22.0 23.0 30.0 31.0 32.0 33.0 40.0 41.0 42.0 43.0


In [124]:
%reset -f

## Reshape a matrix

In [125]:
import numpy as np
a=np.floor(10*np.random.random((3,4)))
a

array([[5., 3., 6., 4.],
       [6., 0., 3., 0.],
       [8., 7., 2., 9.]])

In [126]:
a.ravel()

array([5., 3., 6., 4., 6., 0., 3., 0., 8., 7., 2., 9.])

In [127]:
a=np.floor(10*np.random.random((3,4)))
a

array([[3., 4., 1., 5.],
       [1., 2., 0., 8.],
       [0., 8., 8., 7.]])

In [128]:
a.reshape(1,-1)

array([[3., 4., 1., 5., 1., 2., 0., 8., 0., 8., 8., 7.]])

In [129]:
a.reshape(2,-1)

array([[3., 4., 1., 5., 1., 2.],
       [0., 8., 0., 8., 8., 7.]])

In [130]:
a.reshape(-1,2)

array([[3., 4.],
       [1., 5.],
       [1., 2.],
       [0., 8.],
       [0., 8.],
       [8., 7.]])

## Stack matrics

In [131]:
import numpy as np
a=np.floor(10*np.random.random((2,2)))
print(a)
b=np.floor(10*np.random.random((2,2)))
print(b)


[[5. 0.]
 [4. 8.]]
[[3. 8.]
 [3. 7.]]


In [132]:
np.column_stack((a,b))

array([[5., 0., 3., 8.],
       [4., 8., 3., 7.]])

In [133]:
np.hstack((a,b))

array([[5., 0., 3., 8.],
       [4., 8., 3., 7.]])

In [134]:
np.vstack((a,b))

array([[5., 0.],
       [4., 8.],
       [3., 8.],
       [3., 7.]])

In [135]:
np.row_stack((a,b))

array([[5., 0.],
       [4., 8.],
       [3., 8.],
       [3., 7.]])

In [136]:
%reset -f

## Matrix operation

In [137]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
a=np.arange(0,4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [138]:
a.transpose()

array([[0, 2],
       [1, 3]])

In [139]:
a.T

array([[0, 2],
       [1, 3]])

In [140]:
np.linalg.pinv(a)

array([[-1.50000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  4.21097322e-17]])

In [141]:
a.dot(np.linalg.pinv(a))

array([[1.00000000e+00, 4.21097322e-17],
       [0.00000000e+00, 1.00000000e+00]])

In [142]:
np.trace(a)

3

In [143]:
print(a)
y=np.array([[5],[7]])
np.linalg.solve(a,y)

[[0 1]
 [2 3]]


array([[-4.],
       [ 5.]])

In [144]:
np.linalg.eig(a)

(array([-0.56155281,  3.56155281]),
 array([[-0.87192821, -0.27032301],
        [ 0.48963374, -0.96276969]]))

In [145]:
%reset -f

## Andrew Ng's Advice

In [146]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import pandas as pd

a=np.random.randn(5,1) # instead of a=np.random.randn(5)
print(a)
print(a.T)
print(a.T.dot(a))

%reset -f

[[ 2.14724609]
 [ 0.18341239]
 [-0.23950761]
 [-1.09539781]
 [ 0.69254428]]
[[ 2.14724609  0.18341239 -0.23950761 -1.09539781  0.69254428]]
[[6.38118374]]


# Indexing

In [147]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
y=np.arange(0,35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [148]:
y[np.array([0,2,4]),np.array([0,1,2])] # get [y[0,0], y[2,1], y[4,2]]

array([ 0, 15, 30])